name: pydev

channels:
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - geopandas
  - rasterio
  - shapely
  - pyproj
  - pyogrio
  - osmnx
  - contextily
  - libpysal
  - esda
  - mgwr
  - spglm
  - spreg
  - jupyterlab
  - ipykernel
  - ipywidgets
  - pip:
      - -r requirements.txt